version: '3.8'
services:
  besu:
    image: hyperledger/besu:latest
    volumes:
      - besu-data:/opt/besu/data
      - ./config.toml:/etc/besu/config.toml
      - ./genesis.json:/etc/besu/genesis.json
      - ./private_key:/etc/besu/private_key
    command: ["--config-file=/etc/besu/config.toml"]
    ports:
      - "8545:8545"
      - "8546:8546"
volumes:
  besu-data:
